# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individu_nom', models.CharField(max_length=50)),
                ('individu_prenom_usage', models.CharField(blank=True, max_length=25)),
                ('individu_prenom_supp', models.TextField(blank=True)),
                ('individu_comment', models.TextField(blank=True)),
            ],
        ),
    ]
