# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='individu_mere',
            field=models.ManyToManyField(blank=True, related_name='_individu_individu_mere_+', to='genepoum.Individu'),
        ),
        migrations.AddField(
            model_name='individu',
            name='individu_pere',
            field=models.ManyToManyField(blank=True, related_name='_individu_individu_pere_+', to='genepoum.Individu'),
        ),
    ]
