# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0002_auto_20170512_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='individu_mere',
            field=models.ManyToManyField(blank=True, related_name='mere', to='genepoum.Individu'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='individu_pere',
            field=models.ManyToManyField(blank=True, related_name='pere', to='genepoum.Individu'),
        ),
    ]
