# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0004_auto_20170513_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Qui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_qui_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genepoum.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='individu',
            name='individu_event',
        ),
        migrations.AddField(
            model_name='event_qui',
            name='event_qui_individu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genepoum.Individu'),
        ),
    ]
