# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0008_auto_20170515_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('N', 'Naissance'), ('B', 'Bapt\xe8me'), ('M', 'Mariage'), ('E', 'Enfant'), ('D', 'D\xe9c\xe8s'), ('S', 'S\xe9pulture'), ('X', 'Autre')], default='X', max_length=1),
        ),
    ]
