# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0010_auto_20170517_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicile_adresse', models.CharField(max_length=40)),
                ('domicile_gps', models.CharField(blank=True, max_length=100)),
                ('domicile_description', models.CharField(blank=True, max_length=100)),
                ('domicile_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foyer_periode', models.CharField(max_length=40)),
                ('foyer_fonction', models.CharField(blank=True, max_length=100)),
                ('foyer_comment', models.TextField(blank=True)),
                ('foyer_domicile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genepoum.Domicile')),
                ('foyer_individu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genepoum.Individu')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('N', 'Naissance'), ('B', 'Bapt\xe8me'), ('M', 'Mariage'), ('D', 'D\xe9c\xe8s'), ('S', 'S\xe9pulture'), ('X', 'Autre')], default='X', max_length=1),
        ),
    ]
