# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0011_auto_20170522_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individu',
            options={'ordering': ['individu_nom', 'individu_prenom_usage']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genepoum.Domicile'),
        ),
        migrations.AlterField(
            model_name='event_qui',
            name='event_qui_fonction',
            field=models.CharField(choices=[('BEBE', 'B\xe9b\xe9 (r\xe9serv\xe9 \xe0 la naissance)'), ('BAPTISE', 'Baptis\xe9'), ('EPOUSE', 'Epouse'), ('EPOUX', 'Epoux'), ('MERE', 'M\xe8re'), ('PERE', 'P\xe8re'), ('ENFANT', 'Enfant'), ('FRERE', 'Fr\xe8re'), ('SOEUR', 'Soeur'), ('COUSIN', 'Cousin'), ('FAMILLE', 'Membre de la famille'), ('TEMOIN', 'T\xe9moin'), ('NOTAIRE', 'Notaire'), ('MAIRE', 'Maire'), ('CURE', 'Cur\xe9'), ('MORT', 'Mort'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=100),
        ),
    ]
