# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genepoum', '0011_auto_20170515_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='individu_mere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mere', to='genepoum.Individu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individu',
            name='individu_pere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pere', to='genepoum.Individu'),
            preserve_default=False,
        ),
    ]
